### ISSUE TITLE
Babel issue on new install (ReferenceError: Using removed Babel 5 option: .stage)

### ISSUE THREAD

**Issue by fatlinesofcode** [iaincollins/nextjs-starter#87]
I've just cloned the starter from Master. I've ran npm install but am received in the following issue when i try and build

```
phils-macbook-pro-2:nextjs-starter phil$ npm run build

> nextjs-starter@6.0.3 build /Users/phil/Sites/git/test/nextjs-starter
> next build

> Failed to build
ReferenceError: Using removed Babel 5 option: .stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at buildUnknownError (/Users/phil/Sites/git/test/nextjs-starter/node_modules/@babel/core/lib/config/validation/options.js:95:11)
    at /Users/phil/Sites/git/test/nextjs-starter/node_modules/@babel/core/lib/config/validation/options.js:84:57
    at Array.forEach (<anonymous>)
    at validate (/Users/phil/Sites/git/test/nextjs-starter/node_modules/@babel/core/lib/config/validation/options.js:62:21)
    at /Users/phil/Sites/git/test/nextjs-starter/node_modules/@babel/core/lib/config/config-chain.js:141:36
    at cachedFunction (/Users/phil/Sites/git/test/nextjs-starter/node_modules/@babel/core/lib/config/caching.js:40:17)
    at init (/Users/phil/Sites/git/test/nextjs-starter/node_modules/@babel/core/lib/config/config-chain.js:122:12)
    at /Users/phil/Sites/git/test/nextjs-starter/node_modules/@babel/core/lib/config/config-chain.js:206:17
    at buildRootChain (/Users/phil/Sites/git/test/nextjs-starter/node_modules/@babel/core/lib/config/config-chain.js:85:20)
    at loadPrivatePartialConfig (/Users/phil/Sites/git/test/nextjs-starter/node_modules/@babel/core/lib/config/partial.js:41:53)
    at loadPartialConfig (/Users/phil/Sites/git/test/nextjs-starter/node_modules/@babel/core/lib/config/partial.js:66:16)
    at babelConfig (/Users/phil/Sites/git/test/nextjs-starter/node_modules/next/dist/server/build/webpack.js:88:57)
    at _callee2$ (/Users/phil/Sites/git/test/nextjs-starter/node_modules/next/dist/server/build/webpack.js:164:34)
    at tryCatch (/Users/phil/Sites/git/test/nextjs-starter/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/phil/Sites/git/test/nextjs-starter/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/phil/Sites/git/test/nextjs-starter/node_modules/regenerator-runtime/runtime.js:114:21)
```

Any advice on how to fix?

**Comment by fatlinesofcode** [comment]
re-installed in a new folder and worked fine. weird

**Comment by iaincollins** [comment]
Oh thanks for the follow up! Weird but good to know in case it pops up again
