### ISSUE TITLE
TypeError: OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by coommark** [iaincollins/nextjs-starter#88]
I cloned this repo and npm installed. I am running on Windows 10. When I `npm run dev`, it throws the error below. Kindly help.
```
An error occurred, unable to start the server
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\next_samples\auth-stripped\nextjs-starter\node_modules\passport-oauth2\lib\strategy.js:82:34)
    at new Strategy (C:\next_samples\auth-stripped\nextjs-starter\node_modules\passport-github\lib\strategy.js:62:18)
    at providers.forEach (C:\next_samples\auth-stripped\nextjs-starter\node_modules\next-auth\src\passport-strategies.js:72:18)
    at Array.forEach (<anonymous>)
    at module.exports (C:\next_samples\auth-stripped\nextjs-starter\node_modules\next-auth\src\passport-strategies.js:62:13)
    at module.exports (C:\next_samples\auth-stripped\nextjs-starter\node_modules\next-auth\index.js:132:3)
    at nextApp.prepare.then.then.nextAuthOptions (C:\next_samples\auth-stripped\nextjs-starter\index.js:45:10)
    at run (C:\next_samples\auth-stripped\nextjs-starter\node_modules\core-js\library\modules\es6.promise.js:75:22)
    at C:\next_samples\auth-stripped\nextjs-starter\node_modules\core-js\library\modules\es6.promise.js:92:30
    at flush (C:\next_samples\auth-stripped\nextjs-starter\node_modules\core-js\library\modules\_microtask.js:18:9)
```
I renamed the default `.env.default` file to `.env `but it still fails.

Thank you.

**Comment by coommark** [comment]
Found the issue in the next-auth.providers.js. The providers were not defined.

**Comment by iaincollins** [comment]
Thanks for closing, sorry I haven't be able to respond (I've been on a rather long holiday).

If you have anything relevant to add feedback is always appreciated. I know there are some ongoing issues Windows – and what looks like a major issue with Internet Explorer (not Edge).
